local GameConfig = require(script.Parent.Parent.GameConfig)

local ItemDefinitions = {
	mecha_training_blade_001 = {
		Id = "mecha_training_blade_001",
		Name = "Mechanica Training Blade",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 8,
		AttackMax = 13,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mecha_training_rifle_001 = {
		Id = "mecha_training_rifle_001",
		Name = "Mechanica Training Rifle",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Ranged,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Ranged, Level = 1 },
		AttackMin = 7,
		AttackMax = 15,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mecha_training_reaver_001 = {
		Id = "mecha_training_reaver_001",
		Name = "Mechanica Light Reaver",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Magic,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Magic, Level = 1 },
		AttackMin = 5,
		AttackMax = 10,
		ForceAttackMin = 8,
		ForceAttackMax = 15,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mecha_training_tool_001 = {
		Id = "mecha_training_tool_001",
		Name = "Mechanica Service Tool",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 5,
		AttackMax = 9,
		Defense = 0,
		MaxUpgrade = 7,
	},

	cyborg_training_blade_001 = {
		Id = "cyborg_training_blade_001",
		Name = "Dominion Training Blade",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 9,
		AttackMax = 14,
		Defense = 0,
		MaxUpgrade = 7,
	},

	cyborg_training_launcher_001 = {
		Id = "cyborg_training_launcher_001",
		Name = "Dominion Training Launcher",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Launcher,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Launcher, Level = 1 },
		AttackMin = 12,
		AttackMax = 22,
		Defense = 0,
		MaxUpgrade = 7,
	},

	cyborg_training_tool_001 = {
		Id = "cyborg_training_tool_001",
		Name = "Dominion Utility Tool",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 6,
		AttackMax = 10,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mystic_training_blade_001 = {
		Id = "mystic_training_blade_001",
		Name = "Elyndra Training Blade",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 7,
		AttackMax = 12,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mystic_training_bow_001 = {
		Id = "mystic_training_bow_001",
		Name = "Elyndra Training Bow",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Ranged,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Ranged, Level = 1 },
		AttackMin = 7,
		AttackMax = 14,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mystic_training_staff_001 = {
		Id = "mystic_training_staff_001",
		Name = "Elyndra Training Staff",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Magic,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Magic, Level = 1 },
		AttackMin = 4,
		AttackMax = 9,
		ForceAttackMin = 10,
		ForceAttackMax = 18,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mystic_training_tool_001 = {
		Id = "mystic_training_tool_001",
		Name = "Elyndra Rune Tool",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 5,
		AttackMax = 9,
		Defense = 0,
		MaxUpgrade = 7,
	},

	mecha_training_armor_001 = {
		Id = "mecha_training_armor_001",
		Name = "Mechanica Recruit Armor",
		Category = GameConfig.ItemCategories.Armor,
		Slot = GameConfig.EquipmentSlots.Armor,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Defense, Level = 1 },
		AttackMin = 0,
		AttackMax = 0,
		Defense = 15,
		MaxUpgrade = 7,
	},

	cyborg_training_armor_001 = {
		Id = "cyborg_training_armor_001",
		Name = "Dominion Recruit Frame",
		Category = GameConfig.ItemCategories.Armor,
		Slot = GameConfig.EquipmentSlots.Armor,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Defense, Level = 1 },
		AttackMin = 0,
		AttackMax = 0,
		Defense = 18,
		MaxUpgrade = 7,
	},

	mystic_training_robe_001 = {
		Id = "mystic_training_robe_001",
		Name = "Elyndra Recruit Robe",
		Category = GameConfig.ItemCategories.Armor,
		Slot = GameConfig.EquipmentSlots.Armor,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Defense, Level = 1 },
		AttackMin = 0,
		AttackMax = 0,
		Defense = 11,
		MaxUpgrade = 7,
	},

	upgrader = {
		Id = "upgrader",
		Name = "Upgrader",
		Type = "Tool",
		Category = "Permanent",
		Slot = nil,
		EquipSlot = nil,

		Description = "Permanent item used to open the upgrade interface.",

		Stackable = false,
		MaxStack = 1,
		Consumable = false,
		IsPermanent = true,

		CanTrade = false,
		CanSell = false,
		CanDrop = false,

		SpecialAction = "OpenUpgradeUI",
	},

	talic_ignorant = {
		Id = "talic_ignorant",
		Name = "Ignorant Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for weapon attack upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Ignorant",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_keen = {
		Id = "talic_keen",
		Name = "Keen Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for weapon attack upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Keen",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_destruction = {
		Id = "talic_destruction",
		Name = "Destruction Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for attack percent upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Destruction",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_chaos = {
		Id = "talic_chaos",
		Name = "Chaos Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for critical chance upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Chaos",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_glory = {
		Id = "talic_glory",
		Name = "Glory Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for accuracy upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Glory",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_guard = {
		Id = "talic_guard",
		Name = "Guard Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for defense upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Guard",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_mercy = {
		Id = "talic_mercy",
		Name = "Mercy Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for dodge upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Mercy",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_sacred_fire = {
		Id = "talic_sacred_fire",
		Name = "Sacred Fire Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for fire element upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "SacredFire",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	talic_belief = {
		Id = "talic_belief",
		Name = "Belief Talic",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Talic used for aqua element upgrades.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Talic",
		TalicId = "Belief",
		AppliesTo = GameConfig.ItemCategories.Weapon,
	},

	upgrade_catalyst_low = {
		Id = "upgrade_catalyst_low",
		Name = "Low Catalyst",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Catalyst that slightly improves upgrade success chance.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Catalyst",
		CatalystPower = 0.03,
	},

	upgrade_catalyst_mid = {
		Id = "upgrade_catalyst_mid",
		Name = "Medium Catalyst",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Catalyst that improves upgrade success chance.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Catalyst",
		CatalystPower = 0.06,
	},

	upgrade_catalyst_high = {
		Id = "upgrade_catalyst_high",
		Name = "High Catalyst",
		Category = "UpgradeMaterial",
		Slot = nil,
		EquipSlot = nil,
		Description = "Catalyst that strongly improves upgrade success chance.",
		Stackable = true,
		MaxStack = 99,
		Consumable = true,
		UpgradeRole = "Catalyst",
		CatalystPower = 0.10,
	},
}

return ItemDefinitions
