local GameConfig = require(script.Parent.Parent.GameConfig)

local ItemDefinitions = {
	mecha_training_blade_001 = {
		Id = "mecha_training_blade_001",
		Name = "Mechanica Training Blade",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 8, AttackMax = 13, Defense = 0, MaxUpgrade = 7,
	},
	mecha_training_rifle_001 = {
		Id = "mecha_training_rifle_001",
		Name = "Mechanica Training Rifle",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Ranged,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Ranged, Level = 1 },
		AttackMin = 7, AttackMax = 15, Defense = 0, MaxUpgrade = 7,
	},
	mecha_training_reaver_001 = {
		Id = "mecha_training_reaver_001",
		Name = "Mechanica Light Reaver",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Magic,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Magic, Level = 1 },
		AttackMin = 5, AttackMax = 10, ForceAttackMin = 8, ForceAttackMax = 15,
		Defense = 0, MaxUpgrade = 7,
	},
	mecha_training_tool_001 = {
		Id = "mecha_training_tool_001",
		Name = "Mechanica Service Tool",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 5, AttackMax = 9, Defense = 0, MaxUpgrade = 7,
	},
	cyborg_training_blade_001 = {
		Id = "cyborg_training_blade_001",
		Name = "Dominion Training Blade",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 9, AttackMax = 14, Defense = 0, MaxUpgrade = 7,
	},
	cyborg_training_launcher_001 = {
		Id = "cyborg_training_launcher_001",
		Name = "Dominion Training Launcher",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Launcher,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Launcher, Level = 1 },
		AttackMin = 12, AttackMax = 22, Defense = 0, MaxUpgrade = 7,
	},
	cyborg_training_tool_001 = {
		Id = "cyborg_training_tool_001",
		Name = "Dominion Utility Tool",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 6, AttackMax = 10, Defense = 0, MaxUpgrade = 7,
	},
	mystic_training_blade_001 = {
		Id = "mystic_training_blade_001",
		Name = "Elyndra Training Blade",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 7, AttackMax = 12, Defense = 0, MaxUpgrade = 7,
	},
	mystic_training_bow_001 = {
		Id = "mystic_training_bow_001",
		Name = "Elyndra Training Bow",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Ranged,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Ranged, Level = 1 },
		AttackMin = 7, AttackMax = 14, Defense = 0, MaxUpgrade = 7,
	},
	mystic_training_staff_001 = {
		Id = "mystic_training_staff_001",
		Name = "Elyndra Training Staff",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Magic,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Magic, Level = 1 },
		AttackMin = 4, AttackMax = 9, ForceAttackMin = 10, ForceAttackMax = 18,
		Defense = 0, MaxUpgrade = 7,
	},
	mystic_training_tool_001 = {
		Id = "mystic_training_tool_001",
		Name = "Elyndra Rune Tool",
		Category = GameConfig.ItemCategories.Weapon,
		Slot = GameConfig.EquipmentSlots.Weapon,
		WeaponType = GameConfig.PTTypes.Melee,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Melee, Level = 1 },
		AttackMin = 5, AttackMax = 9, Defense = 0, MaxUpgrade = 7,
	},
	mecha_training_armor_001 = {
		Id = "mecha_training_armor_001",
		Name = "Mechanica Recruit Armor",
		Category = GameConfig.ItemCategories.Armor,
		Slot = GameConfig.EquipmentSlots.Armor,
		FactionId = GameConfig.Factions.MECHA,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Defense, Level = 1 },
		AttackMin = 0, AttackMax = 0, Defense = 15, MaxUpgrade = 7,
	},
	cyborg_training_armor_001 = {
		Id = "cyborg_training_armor_001",
		Name = "Dominion Recruit Frame",
		Category = GameConfig.ItemCategories.Armor,
		Slot = GameConfig.EquipmentSlots.Armor,
		FactionId = GameConfig.Factions.CYBORG,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Defense, Level = 1 },
		AttackMin = 0, AttackMax = 0, Defense = 18, MaxUpgrade = 7,
	},
	mystic_training_robe_001 = {
		Id = "mystic_training_robe_001",
		Name = "Elyndra Recruit Robe",
		Category = GameConfig.ItemCategories.Armor,
		Slot = GameConfig.EquipmentSlots.Armor,
		FactionId = GameConfig.Factions.MYSTIC,
		RequiredLevel = 1,
		RequiredPT = { Type = GameConfig.PTTypes.Defense, Level = 1 },
		AttackMin = 0, AttackMax = 0, Defense = 11, MaxUpgrade = 7,
	},
	    upgrader = {
        Id = "upgrader",
        Name = "Aetherion Upgrader",
        Category = GameConfig.ItemCategories.Material,
        Type = "Utility",
        SpecialAction = "OpenUpgradeUI",
        IsPermanent = true,
        Locked = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        Stackable = false,
        Slots = 0,
        Durability = 0,
        MaxDurability = 0,
    },

    ignorant_talic = {
        Id = "ignorant_talic",
        Name = "Ignorant Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.01,
    },

    keen_talic = {
        Id = "keen_talic",
        Name = "Keen Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.015,
    },

    favor_talic = {
        Id = "favor_talic",
        Name = "Favor Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.02,
    },

    wisdom_talic = {
        Id = "wisdom_talic",
        Name = "Wisdom Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.025,
    },

    sacred_fire_talic = {
        Id = "sacred_fire_talic",
        Name = "Sacred Fire Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.03,
    },

    belief_talic = {
        Id = "belief_talic",
        Name = "Belief Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.035,
    },

    guard_talic = {
        Id = "guard_talic",
        Name = "Guard Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.015,
    },

    destruction_talic = {
        Id = "destruction_talic",
        Name = "Destruction Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.04,
    },

    chaos_talic = {
        Id = "chaos_talic",
        Name = "Chaos Talic",
        Category = GameConfig.ItemCategories.Material,
        Type = "Talic",
        UpgradeRole = "Talic",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.05,
    },

    upgrade_catalyst_low = {
        Id = "upgrade_catalyst_low",
        Name = "Low Upgrade Catalyst",
        Category = GameConfig.ItemCategories.Material,
        Type = "UpgradeCatalyst",
        UpgradeRole = "Catalyst",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.02,
    },

    upgrade_catalyst_medium = {
        Id = "upgrade_catalyst_medium",
        Name = "Medium Upgrade Catalyst",
        Category = GameConfig.ItemCategories.Material,
        Type = "UpgradeCatalyst",
        UpgradeRole = "Catalyst",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.04,
    },

    upgrade_catalyst_high = {
        Id = "upgrade_catalyst_high",
        Name = "High Upgrade Catalyst",
        Category = GameConfig.ItemCategories.Material,
        Type = "UpgradeCatalyst",
        UpgradeRole = "Catalyst",
        Stackable = true,
        CanSell = false,
        CanDrop = false,
        CanTrade = false,
        UpgradePower = 0.06,
    },
}

return ItemDefinitions
